name: Streamlit Deploy

on:
  push:
    branches:
      - main  # Sadece 'main' branch'e yapılan değişikliklerde çalıştırılır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Streamlit için desteklenen Python sürümü

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Streamlit
        run: |
          echo "Streamlit deploy handled by Streamlit Cloud automatically."
