name: Keep Streamlit App Alive
on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Streamlit app
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://elasticleakapp-mcqrcyv9sd9dtxutkee7ws.streamlit.app || true
          echo "Ping completed at $(date)"
